apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-app
spec:
  selector:
    matchLabels:
      app: nginx-app
  replicas: 6
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx-app
    spec:
      volumes: 
        - name: "nginx-data"
          hostPath: 
            path: "/var/lib/nginx"
      containers:
        - image: nginx
          name:  nginx-container
          resources:
            requests:
              cpu: "500m"
              memory: "128Mi"
            limits:
              cpu: "1000m"
              memory: "256Mi"
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          volumeMounts: 
            - mountPath: "/data"
              name: "nginx-data"
