apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: web
    tier: frontend
  namespace: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx
        image: nginx:1.16
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy-deployment
  labels:
    app: haproxy
    tier: frontend
  namespace: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: haproxy
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      containers:
      - name: nginx
        image: nginx:1.16
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: redis-hr
    tier: backend
  namespace: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redis-hr
  template:
    metadata:
      labels:
        app: redis-hr
    spec:
      containers:
      - name: redis
        image: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-backend-deploy
  labels:
    app: redis-fin
    tier: backend
  namespace: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redis-fin
  template:
    metadata:
      labels:
        app: redis-fin
    spec:
      containers:
      - name: redis
        image: redis
